export const EMPLOYEE_DATA = "EMPLOYEE_DATA";
export const EMPLOYEE_DATA_SUCCESS = "EMPLOYEE_DATA_SUCCESS";

export const INSERT_DATA = "INSERT_DATA";
export const INSERT_DATA_SUCCESS = "INSERT_DATA_SUCCESS";

export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";

export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";

export const LOGOUT_SHOW= "CONTACT_SHOW"